#!/bin/sh

# Output format constant (default: .mp4)
# Supported formats: avi, flv, mkv, mov, mp4, webm
output_format="mp4"

channel_depth="$2"

if [ -z $channel_depth ]
    then
#     yt-dlp --cookies-from-browser firefox --no-warnings -f 'bestvideo[height<=720]+bestaudio/best[height<=720]/bestvideo[height<=480]+bestaudio/best[height<=480]' --merge-output-format $output_format --match-filter "!is_live" -ciw -o '%(title)s.%(ext)s' $1
     yt-dlp --no-warnings -f 'bestvideo[height<=720]+bestaudio/best[height<=720]/bestvideo[height<=480]+bestaudio/best[height<=480]' --merge-output-format $output_format --match-filter "!is_live" -ciw -o '%(title)s.%(ext)s' $1
    else
#     yt-dlp --cookies-from-browser firefox --no-warnings -f 'bestvideo[height<=720]+bestaudio/best[height<=720]/bestvideo[height<=480]+bestaudio/best[height<=480]' --merge-output-format $output_format --match-filter "!is_live" --playlist-end $channel_depth -ciw -o '%(title)s.%(ext)s' $1
     yt-dlp --no-warnings -f 'bestvideo[height<=720]+bestaudio/best[height<=720]/bestvideo[height<=480]+bestaudio/best[height<=480]' --merge-output-format $output_format --match-filter "!is_live" --playlist-end $channel_depth -ciw -o '%(title)s.%(ext)s' $1
fi
echo

